<?php
/**
 * Created by PhpStorm.
 * User: gagau
 * Date: 25.02.2019
 * Time: 20:51
 */

include 'Room.php';
class Room3 extends Room

{
    public function __construct($color, $size)
    {
        parent::__construct($color, $size);
    }

    public function size()
    {
        echo 'Моя комната не имеет '.$this->size.' квадратных метров';
    }

    public function getColor()
    {
        parent::getColor(); // TODO: Change the autogenerated stub
    }

}